apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: horos-dashboard
    app.kubernetes.io/instance: horos-dashboard
    argocd.argoproj.io/instance: stage-horos-dashboard
    env: stage
    type: frontend
  name: horos-dashboard
  namespace: staging
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: horos-dashboard
      env: stage
      type: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: horos-dashboard
        app.kubernetes.io/instance: horos-dashboard
        env: stage
        type: frontend
    spec:
      containers:
        - env:
            - name: VITE_BE_URL
              value: 'https://stage-temple.wisdomise.io'
          image: horos-dashboard
          imagePullPolicy: Always
          name: horos-dashboard
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 512M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
