apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ./deployment.yml
- ./service.yml
- ./ingress.yml

commonAnnotations:
  a8r.io/owner: wisdomise
  a8r.io/repository: https://github.com/Wisdomise/horos-dashboard

images:
- digest: sha256:569e5482f8af0c42debf2669aa96a2c1d991b711dc6e0398ebf3a3c1d8af1ddc
  name: horos-dashboard
  newName: 619433764862.dkr.ecr.us-east-1.amazonaws.com/horos-dashboard
