apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ./deployment.yml
- ./service.yml
- ./ingress.yml
- ./ingress-com.yml

commonAnnotations:
  a8r.io/owner: wisdomise
  a8r.io/repository: https://github.com/Wisdomise/horos-dashboard

images:
- digest: sha256:71d6a4d3350abca1edafa327871687ad3b3e137e2bc755fd9a5bf74af528e744
  name: horos-dashboard
  newName: 619433764862.dkr.ecr.us-east-1.amazonaws.com/horos-dashboard
