apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ./deployment.yml
- ./service.yml
- ./ingress.yml
- ./ingress-com.yml

commonAnnotations:
  a8r.io/owner: wisdomise
  a8r.io/repository: https://github.com/Wisdomise/horos-dashboard

images:
- digest: sha256:a4af7f3471bbaacb1293b1c661a6e9f70b923691ccd2943b745df9d1fa1b5f7c
  name: horos-dashboard
  newName: 619433764862.dkr.ecr.us-east-1.amazonaws.com/horos-dashboard
