apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ./deployment.yml
- ./service.yml
- ./ingress.yml
- ./ingress-com.yml

commonAnnotations:
  a8r.io/owner: wisdomise
  a8r.io/repository: https://github.com/Wisdomise/horos-dashboard

images:
- digest: sha256:a149ec2f4fd446645c540c0ce6e95edffd8efac9345a44dd27af76f47ed14db1
  name: horos-dashboard
  newName: 619433764862.dkr.ecr.us-east-1.amazonaws.com/horos-dashboard
