apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ./deployment.yml
- ./service.yml
- ./ingress-wealth.yml
- ./ingress-dashboard.yml

commonAnnotations:
  a8r.io/owner: wisdomise
  a8r.io/repository: https://github.com/Wisdomise/horos-dashboard

images:
- digest: sha256:3351466ee82938bf5ce4eb72a130d018f6376483eda8ec81ff800067712903dd
  name: horos-dashboard
  newName: 619433764862.dkr.ecr.us-east-1.amazonaws.com/horos-dashboard
