apiVersion: v1
kind: Service
metadata:
  labels:
    app: horos-dashboard
    argocd.argoproj.io/instance: stage-horos-dashboard
    env: stage
    type: frontend
  name: horos-dashboard-svc
  namespace: staging
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: horos-dashboard
    env: stage
    type: frontend
  sessionAffinity: None
  type: ClusterIP
