apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: horos-dashboard
    app.kubernetes.io/instance: horos-dashboard
    argocd.argoproj.io/instance: horos-dashboard
    env: production
    type: frontend
  name: horos-dashboard
  namespace: presentation
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: horos-dashboard
      env: production
      type: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: horos-dashboard
        app.kubernetes.io/instance: horos-dashboard
        env: production
        type: frontend
    spec:
      containers:
        - image: horos-dashboard
          imagePullPolicy: Always
          name: horos-dashboard
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 512M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
