apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-cloudflare
    konghq.com/https-redirect-status-code: '302'
    konghq.com/protocols: https
    kubernetes.io/tls-acme: 'true'
  labels:
    app: horos-dashboard
    argocd.argoproj.io/instance: horos-dashboard
    env: production
    name: horos-wealth
    type: frontend
  name: horos-wealth
  namespace: presentation
spec:
  ingressClassName: kong
  rules:
    - host: wealth.wisdomise.io
      http:
        paths:
          - backend:
              service:
                name: horos-dashboard-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - wealth.wisdomise.io
      secretName: horos-wealth-tls