apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: presentation
resources:
- ./deployment.yml
- ./service.yml
- ./ingress.yml


commonAnnotations:
  a8r.io/owner: wisdomise
  a8r.io/repository: https://github.com/Wisdomise/horos-dashboard

images:
- digest: sha256:1d807e4900ade2c6a170f4cfb52bb1b40270603806a5da2e1c029bf120ce8524
  name: horos-dashboard
  newName: 619433764862.dkr.ecr.us-east-1.amazonaws.com/horos-dashboard
