apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: presentation
resources:
- ./deployment.yml
- ./service.yml
- ./ingress.yml


commonAnnotations:
  a8r.io/owner: wisdomise
  a8r.io/repository: https://github.com/Wisdomise/horos-dashboard

images:
- digest: sha256:6843c54feff67200d728cd2a3b8d72a5e43c1184e0ff7c6262901107c8665a84
  name: horos-dashboard
  newName: 619433764862.dkr.ecr.us-east-1.amazonaws.com/horos-dashboard
