apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: presentation
resources:
- ./deployment.yml
- ./service.yml
- ./ingress.yml


commonAnnotations:
  a8r.io/owner: wisdomise
  a8r.io/repository: https://github.com/Wisdomise/horos-dashboard

images:
- digest: sha256:48ad3fb5b3dc9ecf22bed48dc8d25c0242f2fcd0529349af33994aa4f798d16f
  name: horos-dashboard
  newName: 619433764862.dkr.ecr.us-east-1.amazonaws.com/horos-dashboard
